CREATE TABLE SCREENING_LKP (
   SCREENING_ID         BIGINT               NOT NULL,
   SCREENING_NAME       VARCHAR(50)          NULL,
   SCREENING_TYPE       VARCHAR(50)          NULL,
   SCREENING_ACRONYM    VARCHAR(50)          NULL,
   CONSTRAINT PK_SCREENING_LKP PRIMARY KEY (SCREENING_ID)
);

CREATE TABLE PARTICIPANT_MANAGEMENT (
   PARTICIPANT_ID       BIGINT               NOT NULL,
   SCREENING_ID         BIGINT               NULL,
   NHS_NUMBER           BIGINT               NULL,
   RECORD_TYPE     VARCHAR(10)             NULL,
   ELIGIBILITY_FLAG   SMALLINT            NULL,
   REASON_FOR_REMOVAL   VARCHAR(10)              NULL,
   REASON_FOR_REMOVAL_DT DATE                 NULL,
   BUSINESS_RULE_VERSION VARCHAR (10)             NULL,
   EXCEPTION_FLAG       SMALLINT             NULL,
   RECORD_INSERT_DATETIME DATETIME             NULL,
   RECORD_UPDATE_DATETIME DATETIME             NULL,
   CONSTRAINT PK_PARTICIPANT_MANAGEMENT PRIMARY KEY (PARTICIPANT_ID)
);

ALTER TABLE PARTICIPANT_MANAGEMENT
   ADD CONSTRAINT FK_PARTICIP_SCREENING_SCREENIN FOREIGN KEY (SCREENING_ID)
      REFERENCES SCREENING_LKP (SCREENING_ID);

