/*==============================================================*/
/* Table: SCREENING_LKP                                         */
/*==============================================================*/
CREATE TABLE SCREENING_LKP (
   SCREENING_ID         BIGINT               NOT NULL,
   SCREENING_NAME       VARCHAR(50)          NULL,
   SCREENING_TYPE       VARCHAR(50)          NULL,
   SCREENING_ACRONYM    VARCHAR(50)          NULL,
   SCREENING_WORKFLOW_ID VARCHAR(50)          NULL,
   CONSTRAINT PK_SCREENING_LKP PRIMARY KEY (SCREENING_ID)
);

/*==============================================================*/
/* Table: HIGHER_RISK_REFERRAL_REASON_LKP                       */
/*==============================================================*/
CREATE TABLE HIGHER_RISK_REFERRAL_REASON_LKP (
   HIGHER_RISK_REFERRAL_REASON_ID BIGINT               NOT NULL,
   HIGHER_RISK_REFERRAL_REASON_CODE VARCHAR(100)         NOT NULL,
   HIGHER_RISK_REFERRAL_REASON_CODE_DESCRIPTION VARCHAR(200)         NULL,
   CONSTRAINT PK_HIGHER_RISK_REFERRAL_REASON PRIMARY KEY (HIGHER_RISK_REFERRAL_REASON_ID)
);

/*==============================================================*/
/* Table: GENE_CODE_LKP                                         */
/*==============================================================*/
CREATE TABLE GENE_CODE_LKP (
   GENE_CODE_ID         BIGINT               NOT NULL,
   GENE_CODE            VARCHAR(100)         NOT NULL,
   GENE_CODE_DESCRIPTION VARCHAR(200)         NULL,
   CONSTRAINT PK_GENE_CODE_LKP PRIMARY KEY (GENE_CODE_ID)
);


/*==============================================================*/
/* Table: PARTICIPANT_MANAGEMENT                                */
/*==============================================================*/
CREATE TABLE PARTICIPANT_MANAGEMENT (
   PARTICIPANT_ID       BIGINT               NOT NULL,
   SCREENING_ID         BIGINT               NULL,
   NHS_NUMBER           BIGINT               NULL,
   RECORD_TYPE          VARCHAR(10)          NULL,
   ELIGIBILITY_FLAG     SMALLINT             NULL,
   REASON_FOR_REMOVAL   VARCHAR(10)          NULL,
   REASON_FOR_REMOVAL_DT DATE                 NULL,
   BUSINESS_RULE_VERSION VARCHAR(10)          NULL,
   EXCEPTION_FLAG       SMALLINT             NULL,
   RECORD_INSERT_DATETIME DATETIME             NULL,
   RECORD_UPDATE_DATETIME DATETIME             NULL,
   NEXT_TEST_DUE_DATE   DATE                 NULL,
   NEXT_TEST_DUE_DATE_CALC_METHOD VARCHAR(100)         NULL,
   PARTICIPANT_SCREENING_STATUS VARCHAR(100)         NULL,
   SCREENING_CEASED_REASON VARCHAR(100)         NULL,
   IS_HIGHER_RISK       SMALLINT             NULL,
   IS_HIGHER_RISK_ACTIVE SMALLINT             NULL,
   HIGHER_RISK_NEXT_TEST_DUE_DATE DATE                 NULL,
   HIGHER_RISK_REFERRAL_REASON_ID BIGINT               NULL,
   DATE_IRRADIATED      DATE                 NULL,
   GENE_CODE_ID         BIGINT               NULL,
   CONSTRAINT PK_PARTICIPANT_MANAGEMENT PRIMARY KEY (PARTICIPANT_ID)
);

ALTER TABLE PARTICIPANT_MANAGEMENT
   ADD CONSTRAINT FK_PARTICIP_REFERENCE_GENE_COD FOREIGN KEY (GENE_CODE_ID)
      REFERENCES GENE_CODE_LKP (GENE_CODE_ID)
;

ALTER TABLE PARTICIPANT_MANAGEMENT
   ADD CONSTRAINT FK_PARTICIP_REFERENCE_HIGHER_R FOREIGN KEY (HIGHER_RISK_REFERRAL_REASON_ID)
      REFERENCES HIGHER_RISK_REFERRAL_REASON_LKP (HIGHER_RISK_REFERRAL_REASON_ID)
;

ALTER TABLE PARTICIPANT_MANAGEMENT
   ADD CONSTRAINT FK_PARTICIP_SCREENING_SCREENIN FOREIGN KEY (SCREENING_ID)
      REFERENCES SCREENING_LKP (SCREENING_ID)
;
